# Generated by Django 3.2.8 on 2021-10-10 01:02

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_relationship'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='relationship',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='relationship',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
