# Generated by Django 3.2.8 on 2021-10-10 04:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211010_0632'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
