# Generated by Django 3.2.8 on 2021-10-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_profile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
