# Generated by Django 3.2.8 on 2024-04-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_profile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='relationship',
            managers=[
            ],
        ),
    ]
